### ISSUE TITLE
writer / Str to be quoted if contains special chars

### ISSUE THREAD

**Issue by dnsl48** [dnsl48/yamlette#3]
Currently a string containing special chars (e.g. commas) renders "as is", which sometimes interferes with the surrounding structure.
E.g description in this example:
```yaml
{
  uuid: 40a7388d-bb5c-4cc6-8813-9bae9fb24a87,
  symbol: VDA,
  description: VDA, German Automobile Industry Association, Litres,
  children: []
}
```
